// QA Kernel test battery.
//
// Categories:
//   NORMAL    — common questions every user asks
//   HARD      — multi-clause / domain jargon / ambiguous phrasings
//   GAP       — questions that exercise capabilities the kernel was just
//               extended to support (case-type comparison, buffer compliance,
//               late-case detail, rush handling, data-quality)
//   OUT       — out-of-scope / chitchat / adversarial — must deflect, not crash
//   FOLLOWUP  — multi-turn sequences that test entity preservation
//
// Each entry can be either { id, q, category } or { id, sequence: [q1,q2,...], category }.

export const QUESTIONS = [
  // ── NORMAL ───────────────────────────────────────────────────────────────
  { category: "NORMAL", id: "greet_hi",         q: "hi" },
  { category: "NORMAL", id: "greet_hello",      q: "hello there" },
  { category: "NORMAL", id: "greet_hey",        q: "hey" },
  { category: "NORMAL", id: "greet_help",       q: "what can you help with?" },
  { category: "NORMAL", id: "greet_help2",      q: "how do you work?" },
  { category: "NORMAL", id: "main_doing",       q: "how am I doing?" },
  { category: "NORMAL", id: "main_status",      q: "give me a status update" },
  { category: "NORMAL", id: "main_perf",        q: "how's our performance?" },
  { category: "NORMAL", id: "main_score",       q: "what's my score?" },
  { category: "NORMAL", id: "improve_basic",    q: "how can I improve?" },
  { category: "NORMAL", id: "improve_alt",      q: "what should I focus on to do better?" },
  { category: "NORMAL", id: "problems_basic",   q: "what needs attention?" },
  { category: "NORMAL", id: "problems_wrong",   q: "what's wrong right now?" },
  { category: "NORMAL", id: "risk_critical",    q: "show me critical cases" },
  { category: "NORMAL", id: "risk_at_risk",     q: "which cases are at risk?" },
  { category: "NORMAL", id: "score_explain",    q: "why is my score what it is?" },
  { category: "NORMAL", id: "score_drop",       q: "why did my score drop?" },
  { category: "NORMAL", id: "score_breakdown",  q: "score breakdown please" },
  { category: "NORMAL", id: "scenario_3late",   q: "what if 3 cases go late?" },
  { category: "NORMAL", id: "scenario_5early",  q: "what would happen if 5 cases finish 2 days early?" },
  { category: "NORMAL", id: "daily_brief",      q: "give me my daily brief" },
  { category: "NORMAL", id: "morning_brief",    q: "morning brief" },
  { category: "NORMAL", id: "bottlenecks",      q: "where are the bottlenecks?" },
  { category: "NORMAL", id: "bottlenecks_alt",  q: "what's slowing things down?" },
  { category: "NORMAL", id: "trends_basic",     q: "are we trending up or down?" },
  { category: "NORMAL", id: "schema_tables",    q: "what tables are in the database?" },

  // ── HARD: complex / multi-clause / domain jargon ─────────────────────────
  { category: "HARD", id: "compound_status_priority",
    q: "how am I doing today and what should I focus on first?" },
  { category: "HARD", id: "diagnostic_why_problems",
    q: "if my on-time rate is so low, what's actually causing it?" },
  { category: "HARD", id: "speculative_future",
    q: "if nothing changes by Friday, where will my score land?" },
  { category: "HARD", id: "comparative_types",
    q: "compare BBS vs Flex throughput" },
  { category: "HARD", id: "comparative_types2",
    q: "which case type takes longest to finish?" },
  { category: "HARD", id: "comparative_types3",
    q: "are general cases moving faster than BBS?" },
  { category: "HARD", id: "buffer_compliance",
    q: "are we meeting our design and production buffers?" },
  { category: "HARD", id: "buffer_violations",
    q: "which cases are violating buffer rules?" },
  { category: "HARD", id: "late_detail",
    q: "tell me about the cases that completed late this period" },
  { category: "HARD", id: "rush_load",
    q: "how many rush cases are there and is it hurting our score?" },
  { category: "HARD", id: "rush_impact",
    q: "what's the impact of all these rush jobs?" },
  { category: "HARD", id: "data_quality",
    q: "how confident are we in these numbers?" },
  { category: "HARD", id: "data_sample",
    q: "is the sample size big enough to trust these stats?" },
  { category: "HARD", id: "stage_focus_recommend",
    q: "given production is the slowest, what's the best lever I have?" },
  { category: "HARD", id: "negation_handling",
    q: "is there nothing critical right now?" },
  { category: "HARD", id: "domain_jargon_bbs",
    q: "how are the BBS jobs holding up?" },
  { category: "HARD", id: "domain_jargon_handoff",
    q: "are handoffs between design and production going smoothly?" },
  { category: "HARD", id: "ambiguous_short",
    q: "score?" },
  { category: "HARD", id: "ambiguous_pronoun",
    q: "should I be worried?" },
  { category: "HARD", id: "deadline_concern",
    q: "anything due today I need to know about?" },

  // ── GAP: capability extensions ───────────────────────────────────────────
  { category: "GAP", id: "type_compare_velocity",
    q: "compare velocity by case type" },
  { category: "GAP", id: "type_breakdown",
    q: "give me a breakdown by case type" },
  { category: "GAP", id: "buffer_design",
    q: "are design-to-production handoffs hitting their buffer?" },
  { category: "GAP", id: "buffer_overall",
    q: "what's our buffer compliance looking like?" },
  { category: "GAP", id: "late_full_list",
    q: "list every case that completed late" },
  { category: "GAP", id: "late_pattern",
    q: "is there a pattern in the late cases?" },
  { category: "GAP", id: "rush_count",
    q: "how many rush cases are open?" },
  { category: "GAP", id: "rush_reduction",
    q: "what's the rush reduction factor doing to us?" },
  { category: "GAP", id: "quality_confidence",
    q: "how reliable is the score given our sample size?" },

  // ── OUT-OF-RANGE: must deflect gracefully, not crash ─────────────────────
  { category: "OUT", id: "out_weather",      q: "what's the weather today?" },
  { category: "OUT", id: "out_joke",         q: "tell me a joke" },
  { category: "OUT", id: "out_recipe",       q: "how do I make sourdough bread?" },
  { category: "OUT", id: "out_personal",     q: "how are you feeling?" },
  { category: "OUT", id: "out_who",          q: "who are you?" },
  { category: "OUT", id: "out_thanks",       q: "thanks" },
  { category: "OUT", id: "out_code",         q: "write me some Python code" },
  { category: "OUT", id: "out_news",         q: "what's happening in the news today?" },
  { category: "OUT", id: "out_random",       q: "purple monkey dishwasher" },
  { category: "OUT", id: "out_empty",        q: "" },
  { category: "OUT", id: "out_punctuation",  q: "???" },
  { category: "OUT", id: "out_single_word",  q: "okay" },
  { category: "OUT", id: "out_long_ramble",
    q: "i was wondering about a lot of things today and yesterday i think things were going okay but maybe not quite as good as i hoped, you know how it is" },
  { category: "OUT", id: "out_rude",         q: "this is useless" },

  // ── FOLLOWUP: multi-turn sequences ───────────────────────────────────────
  { category: "FOLLOWUP", id: "fup_main_then_why",
    sequence: ["how am I doing?", "why?"] },
  { category: "FOLLOWUP", id: "fup_critical_then_more",
    sequence: ["show me critical cases", "tell me more"] },
  { category: "FOLLOWUP", id: "fup_scenario_then_alt",
    sequence: ["what if 3 cases go late?", "and what if 5?"] },
  { category: "FOLLOWUP", id: "fup_problems_then_fix",
    sequence: ["what's wrong?", "how do I fix it?"] },
];
